#!perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

Perinci::CmdLine::Any->new(
    url => '/App/jsonsel/jsonsel',
    read_config => 0,
    read_env => 0,
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

 % jsonsel file.json "Scalar[value > 3]"


=head1 SEE ALSO

In many cases L<jpath> might be a more convenient tool way to select JSON
elements using L<JSON::Path> syntax.

jq, L<https://stedolan.github.io/jq/>, is a powerful tool to select as well as
manipulate JSON elements.

L<Data::CSel>, L<Data::CSel::WrapStruct>, L<CSel::Examples>

L<yamlsel>, L<orgsel>, L<htmlsel>, L<podsel>, L<ppisel>
