#!perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

Perinci::CmdLine::Any->new(
    url => '/App/jsonsel/jsonsel',
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

 % jsonsel "Scalar[value > 3]" file.json


=head1 SEE ALSO

In many cases L<jpath> might be a more convenient tool way to select JSON
elements using L<JSON::Path> syntax.

jq, L<https://stedolan.github.io/jq/>, is a powerful tool to select as well as
manipulate JSON elements.

L<Data::CSel>, L<Data::CSel::WrapStruct>, L<CSel::Examples>

L<yamlsel>, a similar application but for selecting YAML elements.

L<orgsel>, a similar application but for selecting Org elements.

L<htmlsel>, a similar application but for selecting HTML elements using CSS
selector syntax.
